"""empty message

Revision ID: 433f06b58f6f
Revises: 
Create Date: 2020-10-18 23:13:45.311051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433f06b58f6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
